In [1]:
import sqlite3

In [2]:
import pandas as pd

# Database Creation

In [4]:
# Create Database for Online Book Store
conn = sqlite3.connect("Online Book Store.db")
cursor = conn.cursor()

In [5]:
# Creating Table for Books Information in Database
cursor.execute("""
    DROP TABLE IF EXISTS Books
""")
conn.commit()

cursor.execute("""
    CREATE TABLE Books(
    Book_ID INTEGER PRIMARY KEY,
    Title VARCHAR(100),
    Author VARCHAR(100),
    Genre VARCHAR(50),
    Published_Year INTEGER,
    Price NUMERIC(10, 2),
    Stock INTEGER
    );
""")
conn.commit()

In [6]:
# Adding Books Information in Database
df = pd.read_csv('C:\\Users\\aryan\\OneDrive\\Desktop\\Data Science\\Projects\\SQL\\Books.csv')
df.to_sql(
    "Books",      
    conn,
    if_exists="replace",
    index=False
)

500

In [7]:
# Creating Table for Customers Information in Database
cursor.execute("""
    DROP TABLE IF EXISTS Customers
""")
conn.commit()

cursor.execute("""
    CREATE TABLE Customers(
    Customer_ID INTEGER PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone INTEGER,
    City VARCHAR(50),
    Country VARCHAR(50)
    );
""")
conn.commit()

In [8]:
# Adding Customers Information in Database
df = pd.read_csv('C:\\Users\\aryan\\OneDrive\\Desktop\\Data Science\\Projects\\SQL\\Customers.csv')
df.to_sql(
    "Customers",
    conn,
    if_exists="replace",
    index=False
)

500

In [9]:
# Creating Table for Orders Information in Database
cursor.execute("""
    DROP TABLE IF EXISTS Orders
""")
conn.commit()

cursor.execute("""
    CREATE TABLE Orders(
    Order_ID INTEGER PRIMARY KEY,
    Book_ID INTEGER,
    Customer_ID INTEGER,
    Order_Date DATE,
    Quantity INTEGER,
    Total_Amount NUMERIC(10, 2)
    );
""")
conn.commit()

In [10]:
# Adding Orders Information in Database
df = pd.read_csv('C:\\Users\\aryan\\OneDrive\\Desktop\\Data Science\\Projects\\SQL\\Orders.csv')
df.to_sql(
    "Orders",
    conn,
    if_exists="replace",
    index=False
)

500

# Basic Queries

In [12]:
# T1 :- Retrieve all books in the "Fiction" genre
query1 = """
    SELECT * FROM Books WHERE Genre = "Fiction"
"""

df1 = pd.read_sql_query(query1, conn)

df1

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
1,22,Multi-layered optimizing migration,Wesley Escobar,Fiction,1908,39.23,78
2,28,Expanded analyzing portal,Lisa Coffey,Fiction,1941,37.51,79
3,29,Quality-focused multi-tasking challenge,Katrina Underwood,Fiction,1905,31.12,100
4,31,Implemented encompassing conglomeration,Melissa Taylor,Fiction,2010,21.23,44
5,39,Optimized national process improvement,Megan Goodwin,Fiction,1978,10.99,42
6,40,Adaptive didactic interface,Natalie Gonzalez,Fiction,1923,25.97,94
7,47,Reverse-engineered directional conglomeration,John Christian,Fiction,2006,20.37,90
8,62,Re-contextualized real-time strategy,Nicole Lynch,Fiction,1953,26.34,23
9,63,Polarized heuristic database,Franklin Mack,Fiction,1989,22.38,56
10,100,Synchronized client-server service-desk,James Alvarado,Fiction,1906,49.89,29
11,116,Multi-tiered foreground contingency,Jamie Gates,Fiction,1938,41.82,50
12,125,Public-key analyzing Graphic Interface,Abigail Madden,Fiction,1990,32.41,16
13,130,Realigned context-sensitive pricing structure,Jason Rodriguez,Fiction,2004,6.64,90
14,134,Polarized bandwidth-monitored throughput,Linda Newman,Fiction,1955,35.72,49
15,142,Multi-tiered responsive parallelism,Amanda Wilson,Fiction,1940,48.96,11
16,143,Networked multimedia support,Nancy Goodman,Fiction,2012,43.65,50
17,144,Future-proofed scalable software,Matthew Wolf,Fiction,1945,19.27,90
18,156,Synergistic grid-enabled website,Brandon Black,Fiction,1953,31.68,34
19,173,Ergonomic foreground Graphic Interface,Patrick Williams,Fiction,1948,6.07,100
20,185,Networked object-oriented definition,Kelly Vazquez,Fiction,1940,21.98,10
21,187,Total well-modulated groupware,Kenneth Phillips,Fiction,1989,22.98,7
22,214,Fundamental methodical open architecture,Jeffery Green,Fiction,2005,18.16,47
23,220,Multi-lateral zero-defect matrix,Nicole Hughes,Fiction,1904,16.51,60
24,249,Fundamental national infrastructure,Nancy Austin,Fiction,1928,32.95,58
25,251,Seamless 5thgeneration challenge,Michelle Harris,Fiction,1906,8.87,98
26,252,Down-sized high-level encoding,Gabriela Russell MD,Fiction,1902,12.62,43
27,253,Horizontal didactic structure,Robert Rodriguez,Fiction,1961,11.66,21
28,260,Business-focused methodical application,Brian King,Fiction,1907,49.59,10
29,263,Right-sized bifurcated definition,Kayla Wilkinson,Fiction,1965,9.79,3
30,274,Automated systemic functionalities,Matthew Thomas,Fiction,1903,48.80,72
31,278,Exclusive asymmetric installation,Benjamin Flores,Fiction,1901,48.61,69
32,297,Advanced well-modulated architecture,Chad Craig,Fiction,2016,35.65,2
33,298,Assimilated composite archive,Mark Gibson,Fiction,1957,46.66,62
34,299,Centralized disintermediate array,Donald Wiggins,Fiction,1909,28.19,73
35,302,Ergonomic leadingedge portal,James Curtis,Fiction,1981,28.67,92
36,315,Virtual exuding Internet solution,Anne George,Fiction,2012,42.90,40
37,324,Diverse dynamic contingency,James Duran,Fiction,1993,46.08,23
38,327,Implemented zero-defect product,Kim Lee,Fiction,1984,21.40,29
39,329,Multi-tiered dedicated encryption,Jacob Fischer,Fiction,1973,38.49,27
40,331,Profit-focused systematic project,Dennis Hooper,Fiction,1936,15.36,89
41,342,Digitized regional monitoring,Kenneth Finley,Fiction,1969,17.11,84
42,362,Profit-focused multimedia throughput,Andrea Lucas,Fiction,1933,29.43,64
43,366,Re-contextualized national secured line,Robert Wilson,Fiction,1922,13.10,4
44,367,Universal analyzing support,Eric Taylor,Fiction,1940,29.32,35
45,372,Realigned mobile focus group,Michael Jackson,Fiction,1905,17.73,42
46,373,Exclusive dynamic approach,Michelle Mercado,Fiction,1911,39.09,49
47,403,Persevering incremental strategy,David Miller,Fiction,1928,15.01,82
48,406,De-engineered methodical capacity,James Gonzalez,Fiction,2006,35.79,50
49,408,Decentralized tertiary customer loyalty,William Roberts,Fiction,1946,10.07,2
50,414,Organized directional Internet solution,Amanda Carrillo,Fiction,1999,22.55,93
51,421,Exclusive zero administration superstructure,John Pearson,Fiction,1901,40.05,58
52,437,Customizable directional matrices,Alyssa Lopez,Fiction,1960,44.29,7
53,439,Monitored eco-centric framework,Kelly Rodriguez,Fiction,1970,16.00,94
54,458,Cross-group analyzing matrix,Nancy Griffith,Fiction,1914,37.28,53
55,472,Stand-alone clear-thinking extranet,Craig Dominguez,Fiction,1942,28.09,9
56,479,Balanced grid-enabled architecture,Christian Morales,Fiction,2009,38.27,60
57,480,Adaptive mobile toolset,Andrew James,Fiction,1940,38.15,75
58,481,Automated transitional hardware,Nicole Smith,Fiction,1980,10.55,77
59,495,Horizontal background throughput,Billy Lopez,Fiction,1987,20.31,43

In [13]:
# T2 :- Find books published after the year 1950
query2 = """
    SELECT * FROM Books WHERE Published_Year > 1950
    ORDER BY Published_Year ASC
"""

df2 = pd.read_sql_query(query2, conn)

df2

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,166,Customizable discrete Graphical User Interface,Rebecca Alexander,Romance,1951,11.02,56
1,174,Pre-emptive executive knowledge user,Rebecca Mann,Mystery,1951,37.83,18
2,432,Horizontal disintermediate alliance,Rodney Ward,Non-Fiction,1951,8.84,55
3,43,Function-based zero-defect initiative,Daniel Nunez,Romance,1952,47.39,61
4,150,Phased logistical open system,Jenna Henderson,Biography,1952,31.95,32
...,...,...,...,...,...,...,...
287,426,Triple-buffered upward-trending artificial int...,John Shannon,Biography,2021,32.82,98
288,38,Pre-emptive asynchronous leverage,Courtney Nichols,Fantasy,2022,16.47,72
289,51,Visionary optimizing project,Douglas Bush,Biography,2022,46.30,95
290,83,Sharable regional product,Michael Walker,Biography,2022,8.94,92
291,33,Team-oriented empowering synergy,Sandra Williams,Non-Fiction,2023,35.06,49

In [14]:
# T3 :- List of all customers from the Canada
query3 = """
    SELECT * FROM Customers WHERE Country = "Canada"
"""

df3 = pd.read_sql_query(query3, conn)

df3

,Customer_ID,Name,Email,Phone,City,Country
0,38,Nicholas Harris,christine93@perkins.com,1234567928,Davistown,Canada
1,415,James Ramirez,robert54@hall.com,1234568305,Maxwelltown,Canada
2,468,David Hart,stokesrebecca@gmail.com,1234568358,Thompsonfurt,Canada

In [15]:
# T4 :- Show orders placed in November 2023
query4 = """
    SELECT * FROM Orders WHERE strftime('%Y-%m', Order_Date) == "2023-11"
"""
# SELECT * FROM Orders WHERE order_date BETWEEN '2023-11-01' AND '2023-11-30';
df4 = pd.read_sql_query(query4, conn)

df4

    Order_ID  Customer_ID  Book_ID  Order_Date  Quantity  Total_Amount
0          4          433      343  2023-11-25         7        301.21
1         19          496       60  2023-11-17         9        316.26
2         75          291      375  2023-11-30         5        170.75
3        132          469      333  2023-11-22         7        194.32
4        137          474      471  2023-11-25         8        363.04
5        163          207      384  2023-11-23         3        101.76
6        182          129      293  2023-11-01         7        125.51
7        200          313      303  2023-11-23         1          6.57
8        213          325      447  2023-11-17         7        253.75
9        231           22      384  2023-11-11         1         33.92
10       245          386       97  2023-11-01         9        411.66
11       252          405      387  2023-11-15         5        237.10
12       257          123      403  2023-11-06         1         15.01
13       288            6      128  2023-11-13         1         24.04
14       307          368      133  2023-11-17         1         20.96
15       322          270      112  2023-11-08         2         16.04
16       344          385      218  2023-11-25         5         26.80
17       389          485      391  2023-11-18         2         66.84
18       414           23      234  2023-11-10         1          7.15
19       429          449      146  2023-11-01         7        101.50
20       432          420      168  2023-11-04         3         42.39
21       449          490      222  2023-11-18         1         29.59
22       461          317      196  2023-11-18         9         60.21
23       468          162      237  2023-11-22         6        242.58
24       483          459      202  2023-11-23        10        122.60

In [16]:
# T5 :- Retrieve the total stock of books available
query5 = """
    SELECT SUM(Stock) FROM Books
"""

cursor.execute(query5)

results = cursor.fetchall()
print("Total Number of Books Available:-",results[0][0])

Total Number of Books Available:- 25056

In [17]:
# T6 :- Find the details of the most expensive book
query6 = """
    SELECT * FROM Books WHERE Price = (SELECT MAX(Price) FROM Books)
"""
# SELECT * FROM Books ORDER BY Price DESC LIMIT 1;
df6 = pd.read_sql_query(query6, conn)

df6

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,340,Proactive system-worthy orchestration,Robert Scott,Mystery,1907,49.98,88

In [18]:
# T7 :- Show all customers who ordered more than 1 quantity of a book
query7 = """
    SELECT C.* FROM Customers C
    LEFT JOIN Orders O
    ON O.Customer_ID = C.Customer_ID
    WHERE O.Quantity > 1
"""

df7 = pd.read_sql_query(query7, conn)

df7

,Customer_ID,Name,Email,Phone,City,Country
0,84,Gary Blair,leonardtaylor@bowers.net,1234567974,Lake Paul,Armenia
1,137,Steven Miller,tsummers@yahoo.com,1234568027,North Keith,Papua New Guinea
2,216,Phillip Allen,brianwatkins@gmail.com,1234568106,Kelseyfort,Micronesia
3,433,Corey Wells,swagner@robertson.net,1234568323,East David,Zambia
4,14,John Wood,johnsonalexander@gmail.com,1234567904,Richardsonville,New Caledonia
...,...,...,...,...,...,...
433,216,Phillip Allen,brianwatkins@gmail.com,1234568106,Kelseyfort,Micronesia
434,53,Sandra Coleman,emerritt@yahoo.com,1234567943,Lake Karenmouth,Netherlands Antilles
435,328,Russell Thompson,moorewilliam@hughes.biz,1234568218,Hallshire,Holy See (Vatican City State)
436,152,Rebecca Buckley,fross@hotmail.com,1234568042,East Marymouth,Malawi
437,297,Ryan Mendoza,woodjohn@duncan.com,1234568187,West Kim,Argentina

In [19]:
# T8 :- Retrieve all orders where the total amount exceeds 20
query8 = """
    SELECT * FROM Orders WHERE Total_Amount > 20
"""

df8 = pd.read_sql_query(query8, conn)

df8

     Order_ID  Customer_ID  Book_ID  Order_Date  Quantity  Total_Amount
0           1           84      169  2023-05-26         8        188.56
1           2          137      301  2023-01-23        10        216.60
2           3          216      261  2024-05-27         6         85.50
3           4          433      343  2023-11-25         7        301.21
4           5           14      431  2023-07-26         7        136.36
..        ...          ...      ...         ...       ...           ...
468       496           53      233  2024-09-28         6         62.34
469       497          328      272  2023-04-25        10         51.60
470       498          152      406  2024-03-10         2         71.58
471       499          140       48  2023-08-26         1         24.70
472       500          297      137  2024-06-17         5        131.65

[473 rows x 6 columns]

In [20]:
# T9 :- List all genres available in the Books table
query9 = """
    SELECT DISTINCT(Genre) FROM Books
"""

df9 = pd.read_sql_query(query9, conn)

df9

             Genre
0        Biography
1          Fantasy
2      Non-Fiction
3          Fiction
4          Romance
5  Science Fiction
6          Mystery

In [21]:
# T10 :- Find the book with the lowest stock
query10 = """
    SELECT * FROM Books WHERE Stock = (SELECT MIN(Stock) FROM Books)
"""
# SELECT * FROM Books ORDER BY stock LIMIT 1;
df10 = pd.read_sql_query(query10, conn)

df10

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,44,Networked systemic implementation,Ryan Frank,Science Fiction,1965,13.55,0
1,60,Robust eco-centric capacity,Brian Haney,Biography,1990,35.14,0
2,127,Business-focused real-time benchmark,David Nelson,Science Fiction,1997,11.66,0
3,163,Object-based eco-centric challenge,Douglas Mccarthy,Non-Fiction,1905,19.11,0
4,378,Future-proofed heuristic function,Samantha Mcclain,Romance,1903,6.01,0

In [22]:
# T11 :- Calculate the total revenue generated from all orders
query11 = """
    SELECT SUM(Total_Amount) AS 'Total Revenue' FROM Orders
"""

df11= pd.read_sql_query(query11, conn)

df11

   Total Revenue
0       75628.66

# Advance Queries

In [24]:
# T1 :- Retrieve the total number of books sold from each genre
query = """
    SELECT B.Genre, SUM(O.Quantity) AS 'Total Books Sold' FROM Books B
    JOIN Orders O
    ON B.Book_ID = O.Book_ID
    GROUP BY B.Genre
"""

df = pd.read_sql_query(query, conn)
df

             Genre  Total Books Sold
0        Biography               285
1          Fantasy               446
2          Fiction               225
3          Mystery               504
4      Non-Fiction               351
5          Romance               439
6  Science Fiction               447

In [25]:
# T2 :- Find the average price of books in the "Fantasy" genre
query = """
    SELECT Genre,AVG(Price) AS 'Average Price' FROM Books WHERE Genre = "Fantasy"
"""

df= pd.read_sql_query(query, conn)
df

     Genre  Average Price
0  Fantasy       25.98169

In [26]:
# T3 :- List customers who have placed at least 2 orders
query = """
    WITH count_table AS(SELECT Customer_ID ,COUNT(Customer_ID) AS 'Number_of_Orders' FROM Orders GROUP BY Customer_ID)
    
    SELECT T.Customer_ID, C.Name, T.Number_of_Orders FROM Customers C
    RIGHT JOIN
    (SELECT Customer_ID, Number_of_Orders FROM count_table
    WHERE Number_of_Orders >= 2) T
    ON C.Customer_ID = T.Customer_ID
"""


"""
SELECT o.customer_id, c.name, COUNT(o.Order_id) AS ORDER_COUNT
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY o.customer_id, c.name
HAVING COUNT(Order_id) >=2;
"""

df = pd.read_sql_query(query, conn)
df

     Customer_ID              Name  Number_of_Orders
0              2  Crystal Clements                 2
1              6   Stephen Vasquez                 2
2              8   Matthew Johnson                 2
3             13      Kristine Kim                 2
4             14         John Wood                 2
..           ...               ...               ...
134          485   Andrew Figueroa                 4
135          486     Melanie Kelly                 2
136          495    Patrick Rivera                 2
137          497       Shane Klein                 2
138          500        James York                 2

[139 rows x 3 columns]

In [27]:
# T4 :- Find the most frequently ordered book
query = """
    WITH count_table AS(SELECT Book_ID ,COUNT(Order_ID) AS 'Number_of_Orders' FROM Orders GROUP BY Book_ID)
    
    SELECT B.*,T.Number_of_Orders FROM Books B
    RIGHT JOIN
    (SELECT Book_ID,Number_of_Orders FROM count_table
    WHERE Number_of_Orders == (SELECT MAX(Number_of_Orders) FROM count_table)) T
    ON B.Book_ID = T.Book_ID;
"""

df = pd.read_sql_query(query, conn)
df

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock,Number_of_Orders
0,31,Implemented encompassing conglomeration,Melissa Taylor,Fiction,2010,21.23,44,4
1,73,Realigned multi-tasking installation,Patrick Contreras,Mystery,1933,21.23,39,4
2,88,Robust tangible hardware,Paul Miles,Non-Fiction,1999,40.22,32,4
3,120,Integrated secondary access,Sheena Harris,Non-Fiction,1984,48.03,93,4
4,273,Devolved zero administration process improvement,Emily James,Romance,1929,12.43,23,4
5,333,Advanced responsive extranet,Mark Chavez DDS,Fantasy,1959,27.76,29,4
6,491,Pre-emptive intangible adapter,Michael Hill,Fantasy,1910,14.87,2,4

In [28]:
# T5 :- Show the top 3 most expensive books of 'Fantasy' Genre
query = """
    SELECT * FROM Books WHERE Genre == 'Fantasy'
    ORDER BY Price DESC LIMIT 3
"""

df = pd.read_sql_query(query, conn)
df

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,240,Stand-alone content-based hub,Lisa Ellis,Fantasy,1957,49.90,41
1,462,Innovative 3rdgeneration database,Allison Contreras,Fantasy,1988,49.23,62
2,238,Optimized even-keeled analyzer,Sherri Griffith,Fantasy,1975,48.97,72

In [29]:
# T6 :- Retrieve the total quantity of books sold by each author
query = """
    SELECT B.Author,SUM(O.Quantity) AS 'Total_Quantity_of_Books_Sold' FROM Books B
    JOIN Orders O
    ON B.Book_ID = O.Book_ID
    GROUP BY B.Author
"""
df = pd.read_sql_query(query, conn)
df

               Author  Total_Quantity_of_Books_Sold
0      Aaron Hall Jr.                             4
1        Aaron Rangel                             6
2      Abigail Madden                             5
3        Adrian Avery                             6
4    Alexander Bailey                             6
..                ...                           ...
309    William Turner                             9
310    Yolanda Mclean                             3
311  Zachary Buchanan                             1
312     Zachary Hayes                            15
313  Zachary Williams                            19

[314 rows x 2 columns]

In [30]:
# Authors with more than 1 Book
query = """
    WITH count_table AS(SELECT Author, COUNT(Book_ID) AS 'Total_Quantity' FROM Books
    GROUP BY Author)

    SELECT * FROM count_table WHERE Total_Quantity >1
"""

df = pd.read_sql_query(query, conn)
df

             Author  Total_Quantity
0      David Miller               2
1  Jennifer Johnson               2
2       Joseph Holt               2
3     Joseph Jensen               2
4   Michael Johnson               2
5     Robert Garcia               2
6  Timothy Williams               2

In [31]:
# T7 :- List the cities where customers who spent over $30 are located
query = """
    WITH spent_table AS (
                         SELECT Customer_ID, SUM(Total_Amount) AS 'Total_Spent' FROM Orders
                         GROUP BY Customer_ID
                         )

    SELECT DISTINCT(City) FROM Customers
    WHERE Customer_ID IN (SELECT Customer_ID FROM spent_table WHERE Total_Spent > 30 )
"""

df = pd.read_sql_query(query, conn)
df

                City
0     East Derekberg
1       Hamiltonstad
2     Kirstenborough
3      Lake Benjamin
4    West Monicabury
..               ...
279        Davidview
280  West Billymouth
281       Angelatown
282       Ashleyport
283      Port Angela

[284 rows x 1 columns]

In [32]:
# T8 :- Find the customer who spent the most on orders
query = """
    WITH spent_table AS (
                         SELECT Customer_ID, SUM(Total_Amount) AS 'Total_Spent' FROM Orders
                         GROUP BY Customer_ID
                         )
                
    SELECT * FROM Customers C
    RIGHT JOIN (SELECT Customer_ID, MAX(Total_Spent) FROM spent_table) T
    ON C.Customer_ID = T.Customer_ID
"""

df = pd.read_sql_query(query, conn)
df

,Customer_ID,Name,Email,Phone,City,Country,Customer_ID,MAX(Total_Spent)
0,457,Kim Turner,jennifer45@weiss-perry.com,1234568347,South Rachelview,Cambodia,457,1398.9

In [33]:
# T9 :- Calculate the stock remaining after fulfilling all orders
query = """
     WITH books_ordered AS (
                         SELECT Book_ID, SUM(Quantity) AS 'Total_Books_Ordered' FROM Orders
                         GROUP BY Book_ID
                         )
                         
    SELECT B.*, COALESCE((B.Stock - O.Total_Books_Ordered),B.Stock) AS 'Remaning_Stock' FROM Books B
    LEFT JOIN (SELECT * FROM books_ordered) O
    ON B.Book_ID = O.Book_ID
"""

df = pd.read_sql_query(query, conn)
df

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock,Remaning_Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100,97
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27,22
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16,8
...,...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33,30
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64,64